# Generated by Django 5.2.10 on 2026-02-02 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcription_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CDRRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.CharField(max_length=100, unique=True)),
                ("caller", models.CharField(max_length=100)),
                ("callee", models.CharField(max_length=100)),
                ("call_from", models.CharField(blank=True, max_length=100)),
                ("call_to", models.CharField(blank=True, max_length=100)),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Call duration in seconds"
                    ),
                ),
                (
                    "talk_duration",
                    models.IntegerField(
                        default=0, help_text="Talk duration in seconds"
                    ),
                ),
                ("call_type", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(blank=True, max_length=50)),
                (
                    "recording_file",
                    models.CharField(
                        blank=True,
                        help_text="Recording filename on PBX",
                        max_length=500,
                    ),
                ),
                ("call_time", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CDR Record",
                "verbose_name_plural": "CDR Records",
                "ordering": ["-call_time"],
            },
        ),
        migrations.CreateModel(
            name="YeastarPBXConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default PBX", max_length=100)),
                (
                    "host",
                    models.CharField(
                        help_text="PBX IP address or hostname", max_length=255
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        default=8088,
                        help_text="API port (default: 8088 for HTTPS)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "use_https",
                    models.BooleanField(
                        default=True, help_text="Use HTTPS for API calls"
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="API username", max_length=100),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="API password (will be MD5 hashed)", max_length=100
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        default="v2.0.0",
                        help_text="API version (v1.1.0 or v2.0.0)",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=False, help_text="Automatically sync new recordings"
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=5,
                        help_text="How often to check for new recordings (minutes)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Yeastar PBX Configuration",
                "verbose_name_plural": "Yeastar PBX Configurations",
            },
        ),
        migrations.AddField(
            model_name="transcription",
            name="source",
            field=models.CharField(
                choices=[("upload", "Manual Upload"), ("yeastar", "Yeastar PBX")],
                default="upload",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("downloading", "Downloading"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="cdr_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcription",
                to="transcription_app.cdrrecord",
            ),
        ),
        migrations.AddField(
            model_name="cdrrecord",
            name="pbx_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cdr_records",
                to="transcription_app.yeastarpbxconfig",
            ),
        ),
    ]
